#!/bin/sh

cd ~

export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24

export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland

export LIBVA_DRIVER_NAME=nvidia
export GBM_BACKEND=nvidia-drm
export __GLX_VENDOR_LIBRARY_NAME=nvidia

export __GL_GSYNC_ALLOWED=1
export __GL_SYNC_TO_VBLANK=1

export WLR_NO_HARDWARE_CURSORS=1

export MOZ_ENABLE_WAYLAND=1

export SAL_USE_VCLPLUGIN=qt5

export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_QPA_PLATFORM="wayland;xcb"
export QT_QPA_PLATFORM=wayland
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1

export GDK_BACKEND=wayland,x11

export GRIM_DEFAULT_DIR=/home/lucas/Screenshots

export NNN_ARCHIVE='\.(7z|a|ace|alz|arc|arj|bz|bz2|cab|cpio|deb|gz|jar|lha|lz|lzh|lzma|lzo|rar|rpm|rz|t7z|tar|tbz|tbz2|tgz|tlz|txz|tZ|tzo|war|xpi|xz|Z|zip)$'

export VISUAL=helix
export EDITOR=helix

exec Hyprland
