fm: &fm "JetBrainsMono Nerd Font:size=14"

bar:
  height: 28
  location: bottom
  background: 00000000

  center:
    - clock:
        time-format: "%I:%M %p"
        date-format: "%d/%m/%y"
        content:
          - string: {text: , font: *fm, foreground: 74c7ecff, right-margin: 6}
          - string: {text: "{date}", font: *fm, foreground: 74c7ecff, right-margin: 18}
          - string: {text: , font: *fm, foreground: cba6f7ff, right-margin: 6}
          - string: {text: "{time}", font: *fm, foreground: cba6f7ff}
  
  right:
  - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            right-margin: 10
            conditions:
              state == unknown || state == discharging || state == "not charging":
                - string: {text: "{capacity}%  -  {estimate}", font: *fm, foreground: a6e3a1ff}
              state == charging:
                - string: {text: "{capacity}%  +  {estimate}", font: *fm, foreground: a6e3a1ff}
              state == full:
                - string: {text: "Full", font: *fm, foreground: a6e3a1ff}
  
  left:
    - script:
        path: /home/lucas/.config/yambar/scripts/yambar-hyprland-wses
        anchors:
          ws_focused: &ws_focused ffffffff
          ws_active: &ws_active ffffffff
          ws_other: &ws_other cba6f7ff
          ws_rm: &ws_rm 10  
        content:
          list:
            left-margin: 10
            spacing: 0
            items:
              - map:
                  default:
                    string: { text: "1", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 2:
                      empty: {}
                    workspace_1_focused:
                      string: { text: "1", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_1_active:
                      string: { text: "1", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_1_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "2", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 3:
                      empty: {}
                    workspace_2_focused:
                      string: { text: "2", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_2_active:
                      string: { text: "2", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_2_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "3", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 4:
                      empty: {}
                    workspace_3_focused:
                      string: { text: "3", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_3_active:
                      string: { text: "3", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_3_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "4", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 5:
                      empty: {}
                    workspace_4_focused:
                      string: { text: "4", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_4_active:
                      string: { text: "4", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_4_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "5", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 6:
                      empty: {}
                    workspace_5_focused:
                      string: { text: "5", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_5_active:
                      string: { text: "5", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_5_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "6", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 7:
                      empty: {}
                    workspace_6_focused:
                      string: { text: "6", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_6_active:
                      string: { text: "6", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_6_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "7", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 8:
                      empty: {}
                    workspace_7_focused:
                      string: { text: "7", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_7_active:
                      string: { text: "7", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_7_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "8", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 9:
                      empty: {}
                    workspace_8_focused:
                      string: { text: "8", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_8_active:
                      string: { text: "8", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_8_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "9", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 10:
                      empty: {}
                    workspace_9_focused:
                      string: { text: "9", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_9_active:
                      string: { text: "9", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_9_windows == 0:
                      empty: {}
              - map:
                  default:
                    string: { text: "10", font: *fm, foreground: *ws_other, right-margin: *ws_rm }
                  conditions:
                    workspace_count < 11:
                      empty: {}
                    workspace_10_focused:
                      string: { text: "10", font: *fm, foreground: *ws_focused, right-margin: *ws_rm }
                    workspace_10_active:
                      string: { text: "10", font: *fm, foreground: *ws_active, right-margin: *ws_rm }
                    workspace_10_windows == 0:
                      empty: {}
