fm: &fm "JetBrainsMono Nerd Font:size=14"

bar:
  height: 28
  location: bottom
  background: 00000000

  center:
    - clock:
        time-format: "%I:%M %p"
        date-format: "%d/%m/%y"
        content:
          - string: {text: , font: *fm, foreground: 74c7ecff, right-margin: 6}
          - string: {text: "{date}", font: *fm, foreground: 74c7ecff, right-margin: 18}
          - string: {text: , font: *fm, foreground: cba6f7ff, right-margin: 6}
          - string: {text: "{time}", font: *fm, foreground: cba6f7ff}
  
  right:
  - battery:
        name: BAT0
        poll-interval: 30000
        content:
          map:
            right-margin: 10
            conditions:
              state == unknown || state == discharging || state == "not charging":
                - string: {text: "{capacity}%  -  {estimate}", font: *fm, foreground: a6e3a1ff}
              state == charging:
                - string: {text: "{capacity}%  +  {estimate}", font: *fm, foreground: a6e3a1ff}
              state == full:
                - string: {text: "Full", font: *fm, foreground: a6e3a1ff}
  
  left:
    - script:
        path: /home/lucas/.config/yambar/scripts/yambar-hyprland-wses
        anchors:
          ws_focused: &ws_focused ffffffff
          ws_active: &ws_active ffffffff
          ws_empty: &ws_empty 00000000
          ws_other: &ws_other cba6f7ff  
        # you can use `{workspace_N}` here to use the workspace name
          # assigned by Hyprland instead of hard-coding one here. That
          # name is, as far as I can tell, always just the index of the
          # workspace though, so not all that valuable.
          ws_1: &ws_1 "1"
          ws_2: &ws_2 "2"
          ws_3: &ws_3 "3"
          ws_4: &ws_4 "4"
          ws_5: &ws_5 "5"
          ws_6: &ws_6 "6"
          ws_7: &ws_7 "7"
          ws_8: &ws_8 "8"
          ws_9: &ws_9 "9"
          ws_10: &ws_10 "10"
        content:
          list:
            left-margin: 10
            spacing: 6
            items:
              - map:
                  default:
                    string: { text: *ws_1, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 2:
                      # if you replace all of these empty: entries with
                      #
                      #   string: { text: *ws_N, foreground: *ws_empty }
                      #
                      # instead, then you'll always see the full
                      # workspace list. however, you'll be unable to use
                      # `{workspace_N}` as the workspace names in the
                      # anchors list above.
                      empty: {}
                    workspace_1_focused:
                      string: { text: *ws_1, font: *fm, foreground: *ws_focused }
                    workspace_1_active:
                      string: { text: *ws_1, font: *fm, foreground: *ws_active }
                    workspace_1_windows == 0:
                      string: { text: *ws_1, font: *fm, foreground: *ws_empty }
              # All of the maps below are identical to the one above,
              # except with N++.
              - map:
                  default:
                    string: { text: *ws_2, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 3:
                      empty: {}
                    workspace_2_focused:
                      string: { text: *ws_2, font: *fm, foreground: *ws_focused }
                    workspace_2_active:
                      string: { text: *ws_2, font: *fm, foreground: *ws_active }
                    workspace_2_windows == 0:
                      string: { text: *ws_2, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_3, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 4:
                      empty: {}
                    workspace_3_focused:
                      string: { text: *ws_3, font: *fm, foreground: *ws_focused }
                    workspace_3_active:
                      string: { text: *ws_3, font: *fm, foreground: *ws_active }
                    workspace_3_windows == 0:
                      string: { text: *ws_3, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_4, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 5:
                      empty: {}
                    workspace_4_focused:
                      string: { text: *ws_4, font: *fm, foreground: *ws_focused }
                    workspace_4_active:
                      string: { text: *ws_4, font: *fm, foreground: *ws_active }
                    workspace_4_windows == 0:
                      string: { text: *ws_4, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_5, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 6:
                      empty: {}
                    workspace_5_focused:
                      string: { text: *ws_5, font: *fm, foreground: *ws_focused }
                    workspace_5_active:
                      string: { text: *ws_5, font: *fm, foreground: *ws_active }
                    workspace_5_windows == 0:
                      string: { text: *ws_5, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_6, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 7:
                      empty: {}
                    workspace_6_focused:
                      string: { text: *ws_6, font: *fm, foreground: *ws_focused }
                    workspace_6_active:
                      string: { text: *ws_6, font: *fm, foreground: *ws_active }
                    workspace_6_windows == 0:
                      string: { text: *ws_6, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_7, foreground: *ws_other }
                  conditions:
                    workspace_count < 8:
                      empty: {}
                    workspace_7_focused:
                      string: { text: *ws_7, font: *fm, foreground: *ws_focused }
                    workspace_7_active:
                      string: { text: *ws_7, font: *fm, foreground: *ws_active }
                    workspace_7_windows == 0:
                      string: { text: *ws_7, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_8, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 9:
                      empty: {}
                    workspace_8_focused:
                      string: { text: *ws_8, font: *fm, foreground: *ws_focused }
                    workspace_8_active:
                      string: { text: *ws_8, font: *fm, foreground: *ws_active }
                    workspace_8_windows == 0:
                      string: { text: *ws_8, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_9, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count < 10:
                      empty: {}
                    workspace_9_focused:
                      string: { text: *ws_9, font: *fm, foreground: *ws_focused }
                    workspace_9_active:
                      string: { text: *ws_9, font: *fm, foreground: *ws_active }
                    workspace_9_windows == 0:
                      string: { text: *ws_9, font: *fm, foreground: *ws_empty }
              - map:
                  default:
                    string: { text: *ws_10, font: *fm, foreground: *ws_other }
                  conditions:
                    workspace_count <= 10:
                      empty: {}
                    workspace_10_focused:
                      string: { text: *ws_10, font: *fm, foreground: *ws_focused }
                    workspace_10_active:
                      string: { text: *ws_10, font: *fm, foreground: *ws_active }
                    workspace_10_windows == 0:
                      string: { text: *ws_10, font: *fm, foreground: *ws_empty }